import type { Metadata } from "next";
import "@/styles/globals.css"
import AppWalletProvider from "@/lib/AppWalletProvider";
import { Toaster } from "react-hot-toast";
import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
      <Toaster reverseOrder={true}/>
      <AppWalletProvider>{children}</AppWalletProvider>
      </body>
    </html>
  );
}
